// Original manga catalog — all titles and authors invented for this mockup.
// No real series referenced. Solid warm-tone "covers" with title typography.

const MANGA_CATALOG = [
  {
    id: "still-water",
    title: "Still Water",
    author: "R. Inoue",
    year: 2023,
    chapters: 47,
    tags: ["Slice of life", "Drama"],
    type: "Manga",
    direction: "RTL",
    cover: "#3a2820",
    accent: "#c9956b",
    synopsis: "A retired ferry captain returns to the inland sea after thirty years away, and finds the village he left has been waiting for him in ways he did not expect.",
    featured: true,
    rating: 4.7,
    pages: 18,
  },
  {
    id: "lantern-quarter",
    title: "Lantern Quarter",
    author: "M. Sato",
    year: 2024,
    chapters: 12,
    tags: ["Mystery", "Historical"],
    type: "Manga",
    direction: "RTL",
    cover: "#2a1f1a",
    accent: "#a4724b",
    synopsis: "Edo, late autumn. A clerk who can read the small handwriting of the dead is summoned to a teahouse where someone has gone missing without leaving a body.",
    rating: 4.5,
    pages: 22,
  },
  {
    id: "the-glassblower",
    title: "The Glassblower",
    author: "K. Hayashi",
    year: 2022,
    chapters: 86,
    tags: ["Drama", "Coming of age"],
    type: "Manga",
    direction: "RTL",
    cover: "#473023",
    accent: "#d9a474",
    synopsis: "A girl apprenticed against her will discovers that her teacher is shaping more than glass.",
    rating: 4.8,
    pages: 20,
  },
  {
    id: "north-of-eight",
    title: "North of Eight",
    author: "T. Mori",
    year: 2024,
    chapters: 8,
    tags: ["Sci-fi", "Quiet"],
    type: "Webtoon",
    direction: "TTB",
    cover: "#1f2624",
    accent: "#7c9a8a",
    synopsis: "Eight stations, one line, and a conductor who has begun to notice the same passenger riding through every dawn.",
    rating: 4.6,
    pages: 60,
  },
  {
    id: "the-rented-room",
    title: "The Rented Room",
    author: "S. Aoki",
    year: 2023,
    chapters: 33,
    tags: ["Romance", "Slow"],
    type: "Manga",
    direction: "RTL",
    cover: "#3d2a26",
    accent: "#c08a7b",
    synopsis: "Two strangers share a rent agreement and the soft economy of small kindnesses.",
    rating: 4.4,
    pages: 24,
  },
  {
    id: "blue-hour",
    title: "Blue Hour",
    author: "Y. Tanaka",
    year: 2024,
    chapters: 19,
    tags: ["Mystery", "Urban"],
    type: "Manga",
    direction: "RTL",
    cover: "#1f2531",
    accent: "#7d8aa1",
    synopsis: "A photographer who only works between 4:30 and 5:15 in the morning starts catching the same man in the corner of every frame.",
    rating: 4.3,
    pages: 21,
  },
  {
    id: "low-tide",
    title: "Low Tide",
    author: "H. Kobayashi",
    year: 2021,
    chapters: 124,
    tags: ["Drama", "Family"],
    type: "Manga",
    direction: "RTL",
    cover: "#2e2419",
    accent: "#b39564",
    synopsis: "Three siblings inherit a kelp farm and the quiet debts of a father who never explained himself.",
    rating: 4.9,
    pages: 19,
  },
  {
    id: "iron-gardener",
    title: "Iron Gardener",
    author: "F. Watanabe",
    year: 2023,
    chapters: 41,
    tags: ["Fantasy", "Mythic"],
    type: "Manga",
    direction: "RTL",
    cover: "#2a2218",
    accent: "#a88b58",
    synopsis: "A swordsmith who has stopped making weapons begins growing them instead.",
    rating: 4.6,
    pages: 23,
  },
  {
    id: "twelve-letters",
    title: "Twelve Letters",
    author: "N. Yamamoto",
    year: 2024,
    chapters: 6,
    tags: ["Romance", "Epistolary"],
    type: "Webtoon",
    direction: "TTB",
    cover: "#3b2823",
    accent: "#cc9482",
    synopsis: "Twelve letters, twelve weeks, two people who have not yet met.",
    rating: 4.7,
    pages: 80,
  },
  {
    id: "the-cartographer",
    title: "The Cartographer",
    author: "I. Nakamura",
    year: 2022,
    chapters: 67,
    tags: ["Adventure", "Historical"],
    type: "Manga",
    direction: "RTL",
    cover: "#1e2820",
    accent: "#7d9b78",
    synopsis: "A mapmaker is hired to draw a country that may not exist, and finds it begins to draw him back.",
    rating: 4.5,
    pages: 22,
  },
  {
    id: "the-quiet-house",
    title: "The Quiet House",
    author: "E. Suzuki",
    year: 2024,
    chapters: 14,
    tags: ["Horror", "Atmospheric"],
    type: "Manga",
    direction: "RTL",
    cover: "#1a1715",
    accent: "#8a6a5a",
    synopsis: "A home renovation reveals rooms that had not been on any plan.",
    rating: 4.4,
    pages: 20,
  },
  {
    id: "salt-and-paper",
    title: "Salt and Paper",
    author: "A. Fujita",
    year: 2023,
    chapters: 28,
    tags: ["Slice of life", "Food"],
    type: "Manga",
    direction: "RTL",
    cover: "#3c2e1f",
    accent: "#c4a06a",
    synopsis: "A failing stationery shop shares a wall with a thriving pickle vendor. They begin to share more than that.",
    rating: 4.6,
    pages: 18,
  },
];

const COLLECTIONS = [
  { id: "quiet", title: "Quiet stories", subtitle: "For long evenings", ids: ["still-water", "the-rented-room", "low-tide", "salt-and-paper"] },
  { id: "mystery", title: "Things that won't sit still", subtitle: "Mystery & atmosphere", ids: ["lantern-quarter", "blue-hour", "the-quiet-house", "the-cartographer"] },
  { id: "ongoing", title: "Updated this week", subtitle: "Fresh chapters", ids: ["north-of-eight", "twelve-letters", "iron-gardener", "the-glassblower"] },
];

const CONTINUE_READING = [
  { id: "still-water", chapter: 23, page: 9, ofPages: 18, when: "2 hours ago" },
  { id: "low-tide", chapter: 88, page: 14, ofPages: 19, when: "Yesterday" },
  { id: "north-of-eight", chapter: 5, page: 32, ofPages: 60, when: "3 days ago" },
];

const EDITORIAL_PICK = {
  id: "still-water",
  pull: "He had not expected the harbor to be smaller. He had expected, if anything, that thirty years away would have made everything else smaller, and the harbor by contrast enormous.",
  byline: "Editor's pick · Issue 14",
};

window.MANGA_CATALOG = MANGA_CATALOG;
window.COLLECTIONS = COLLECTIONS;
window.CONTINUE_READING = CONTINUE_READING;
window.EDITORIAL_PICK = EDITORIAL_PICK;
window.findManga = (id) => MANGA_CATALOG.find(m => m.id === id);
